apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbrs-app-tweckwerth
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hbrs-app-tweckwerth
  template:
    metadata:
      labels:
        app: hbrs-app-tweckwerth
    spec:
      containers:
        - name: hbrs-app-tweckwerth
          image: hbrs-app-tweckwerth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: hbrs-app-tweckwerth-balancer
spec:
  selector:
    app: hbrs-app-tweckwerth
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
